name: Notificar PR no Discord

on:
  pull_request:
    types: [opened, closed]  # Abriu ou fechou (merge)
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Preparar mensagem
        id: msg
        run: |
          TITLE="${{ github.event.pull_request.title }}"
          URL="${{ github.event.pull_request.html_url }}"
          AUTHOR="${{ github.event.pull_request.user.login }}"
          ACTION="${{ github.event.action }}"
          BASE="${{ github.event.pull_request.base.ref }}"
          HEAD="${{ github.event.pull_request.head.ref }}"
          NUMBER="${{ github.event.pull_request.number }}"
          MERGED="${{ github.event.pull_request.merged }}"
          REPO="${{ github.repository }}"

          if [ "$ACTION" = "opened" ]; then
            STATUS="🚀 Nova PR"
          elif [ "$ACTION" = "closed" ] && [ "$MERGED" = "true" ]; then
            STATUS="✅ PR mergeada"
          else
            echo "Evento não relevante para notificação."
            exit 0
          fi

          cat > payload.json <<EOF
          {
            "thread_name": "${STATUS}: ${TITLE} #${NUMBER}",
            "embeds": [
              {
                "title": "${STATUS}: ${TITLE} #${NUMBER}",
                "url": "${URL}",
                "description": "Autor: **${AUTHOR}**\\nBranches: \`${HEAD}\` → \`${BASE}\`",
                "fields": [
                  { "name": "Ação", "value": "\`${ACTION}\`", "inline": true },
                  { "name": "Repositório", "value": "\`${REPO}\`", "inline": true }
                ]
              }
            ],
            "allowed_mentions": { "parse": [] }
          }
          EOF

          echo "Payload construído:"
          cat payload.json

      - name: Enviar para Discord (canal de Fórum)
        run: |
          curl -sS -H "Content-Type: application/json" \
               -d @payload.json \
               "${{ secrets.DISCORD_WEBHOOK }}?wait=true"
